import type { Engagement } from "@/types/engagement";
import type { AuditDocument } from "@/types/document";
import type { ChatMessage, Citation } from "@/types/chat";

export const mockEngagements: Engagement[] = [
  {
    id: "eng_001",
    name: "ISO 27001 ISMS Audit 2025",
    description: "Annual information security management system audit for Acme Corp",
    status: "active",
    entityName: "Acme Corporation",
    entityId: "ent_001",
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    framework: "ISO 27001:2022",
    members: [
      { id: "m1", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "audit_manager" },
      { id: "m2", userId: "usr_003", name: "James Wilson", email: "auditor@audit.dev", role: "auditor" },
      { id: "m3", userId: "usr_004", name: "Maria Garcia", email: "maria@audit.dev", role: "auditor" },
    ],
    stats: { documentCount: 47, queryCount: 128, findingCount: 3, coveragePercent: 72 },
    createdAt: "2025-01-15T08:00:00Z",
    updatedAt: "2025-06-10T14:30:00Z",
    lastActivityAt: "2025-06-10T14:30:00Z",
  },
  {
    id: "eng_002",
    name: "SOX IT Controls Review",
    description: "SOX Section 404 IT general controls testing for fiscal year 2025",
    status: "active",
    entityName: "Globex Industries",
    entityId: "ent_002",
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    framework: "SOX / COSO",
    members: [
      { id: "m4", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "audit_manager" },
      { id: "m5", userId: "usr_005", name: "David Kim", email: "david@audit.dev", role: "auditor" },
    ],
    stats: { documentCount: 92, queryCount: 256, findingCount: 7, coveragePercent: 85 },
    createdAt: "2025-02-01T09:00:00Z",
    updatedAt: "2025-06-09T11:00:00Z",
    lastActivityAt: "2025-06-09T11:00:00Z",
  },
  {
    id: "eng_003",
    name: "GDPR Compliance Assessment",
    description: "Data protection compliance review for EU operations",
    status: "review",
    entityName: "Acme Corporation",
    entityId: "ent_001",
    periodStart: "2025-01-01",
    periodEnd: "2025-06-30",
    framework: "GDPR",
    members: [
      { id: "m6", userId: "usr_003", name: "James Wilson", email: "auditor@audit.dev", role: "auditor" },
    ],
    stats: { documentCount: 31, queryCount: 64, findingCount: 2, coveragePercent: 91 },
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-06-08T16:00:00Z",
    lastActivityAt: "2025-06-08T16:00:00Z",
  },
  {
    id: "eng_004",
    name: "Vendor Risk Assessment Q1",
    description: "Third-party vendor risk assessment for critical vendors",
    status: "closed",
    entityName: "Globex Industries",
    entityId: "ent_002",
    periodStart: "2025-01-01",
    periodEnd: "2025-03-31",
    framework: "Internal SOP",
    members: [
      { id: "m7", userId: "usr_005", name: "David Kim", email: "david@audit.dev", role: "auditor" },
    ],
    stats: { documentCount: 18, queryCount: 42, findingCount: 1, coveragePercent: 100 },
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-04-15T12:00:00Z",
    lastActivityAt: "2025-04-15T12:00:00Z",
  },
  {
    id: "eng_005",
    name: "Change Management ITGC",
    description: "IT general controls audit focusing on change management processes",
    status: "planning",
    entityName: "Acme Corporation",
    entityId: "ent_001",
    periodStart: "2025-07-01",
    periodEnd: "2025-12-31",
    framework: "COBIT 2019",
    members: [
      { id: "m8", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "audit_manager" },
    ],
    stats: { documentCount: 5, queryCount: 0, findingCount: 0, coveragePercent: 0 },
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2025-06-05T10:00:00Z",
    lastActivityAt: "2025-06-05T10:00:00Z",
  },
];

export const mockDocuments: AuditDocument[] = [
  {
    id: "doc_001",
    title: "ISO 27001:2022 Standard Full Text",
    docType: "standard",
    sourceSystem: "upload",
    confidentialityLevel: "internal",
    engagementId: "eng_001",
    framework: "ISO 27001:2022",
    version: 1,
    pageCount: 42,
    fileSize: 2450000,
    mimeType: "application/pdf",
    chunkCount: 186,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-01-20T08:00:00Z",
  },
  {
    id: "doc_002",
    title: "Acme Corp - Information Security Policy v3.2",
    docType: "policy",
    sourceSystem: "sharepoint",
    sourceUri: "https://sharepoint.acme.com/docs/is-policy-v3.2.pdf",
    confidentialityLevel: "confidential",
    engagementId: "eng_001",
    entityId: "ent_001",
    owner: "CISO Office",
    businessUnit: "Information Security",
    framework: "ISO 27001:2022",
    version: 3,
    pageCount: 28,
    fileSize: 1800000,
    mimeType: "application/pdf",
    chunkCount: 94,
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-03-15T14:00:00Z",
  },
  {
    id: "doc_003",
    title: "Access Control Evidence - Q2 2025",
    docType: "evidence",
    sourceSystem: "upload",
    confidentialityLevel: "confidential",
    engagementId: "eng_001",
    entityId: "ent_001",
    controlId: "AC-01",
    periodStart: "2025-04-01",
    periodEnd: "2025-06-30",
    version: 1,
    pageCount: 15,
    fileSize: 890000,
    mimeType: "application/pdf",
    chunkCount: 42,
    createdAt: "2025-06-02T09:00:00Z",
    updatedAt: "2025-06-02T09:00:00Z",
  },
  {
    id: "doc_004",
    title: "Change Management Procedure",
    docType: "policy",
    sourceSystem: "confluence",
    confidentialityLevel: "internal",
    engagementId: "eng_002",
    entityId: "ent_002",
    controlId: "CHG-01",
    version: 2,
    pageCount: 12,
    fileSize: 650000,
    mimeType: "application/pdf",
    chunkCount: 38,
    createdAt: "2025-02-10T11:00:00Z",
    updatedAt: "2025-05-20T09:00:00Z",
  },
];

export const mockCitations: Citation[] = [
  {
    id: "cit_001",
    documentId: "doc_001",
    documentTitle: "ISO 27001:2022 Standard Full Text",
    chunkId: "chunk_042",
    pageNumber: 14,
    sectionPath: "Clause 6.1.2 - Information security risk assessment",
    snippet: "The organization shall define and apply an information security risk assessment process that establishes and maintains information security risk criteria including risk acceptance criteria and criteria for performing information security risk assessments.",
    score: 0.94,
    retrievalType: "hybrid",
  },
  {
    id: "cit_002",
    documentId: "doc_002",
    documentTitle: "Acme Corp - Information Security Policy v3.2",
    chunkId: "chunk_018",
    pageNumber: 8,
    sectionPath: "Section 4.2 - Risk Assessment Methodology",
    snippet: "Acme Corp conducts risk assessments annually and upon significant changes. The methodology follows the ISO 27005 framework with a 5x5 risk matrix for likelihood and impact scoring.",
    score: 0.87,
    retrievalType: "vector",
  },
  {
    id: "cit_003",
    documentId: "doc_003",
    documentTitle: "Access Control Evidence - Q2 2025",
    chunkId: "chunk_007",
    pageNumber: 3,
    sectionPath: "Section 2 - User Access Review Results",
    snippet: "The quarterly access review for Q2 2025 covered 342 active user accounts across 12 critical systems. 98.5% of accounts were confirmed as appropriately provisioned.",
    score: 0.82,
    retrievalType: "fulltext",
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg_001",
    role: "user",
    content: "What are the ISO 27001 requirements for risk assessment?",
    timestamp: "2025-06-10T14:00:00Z",
  },
  {
    id: "msg_002",
    role: "assistant",
    content: "Based on the ISO 27001:2022 standard, the requirements for risk assessment are defined in **Clause 6.1.2**:\n\n1. **Define risk assessment process** — The organization must establish and maintain criteria for risk acceptance and for performing risk assessments.\n\n2. **Identify risks** — Identify risks associated with the loss of confidentiality, integrity, and availability for information within the ISMS scope.\n\n3. **Analyze risks** — Assess the realistic likelihood of occurrence and the potential consequences (impact) of the identified risks.\n\n4. **Evaluate risks** — Compare risk analysis results with established criteria to determine which risks need treatment.\n\nAccording to Acme Corp's Information Security Policy (v3.2), the organization follows the **ISO 27005 framework** with a 5x5 risk matrix for likelihood and impact scoring, conducting assessments **annually and upon significant changes**.",
    citations: [mockCitations[0], mockCitations[1]],
    confidence: 0.91,
    confidenceLevel: "high",
    explanation: "Retrieved from both the ISO standard text and the internal policy document via hybrid search. High confidence due to direct clause match and supporting internal policy.",
    retrievalMode: "hybrid",
    latencyMs: 1240,
    timestamp: "2025-06-10T14:00:03Z",
  },
  {
    id: "msg_003",
    role: "user",
    content: "Show me the latest access review evidence for Q2 2025",
    timestamp: "2025-06-10T14:02:00Z",
  },
  {
    id: "msg_004",
    role: "assistant",
    content: "Here are the findings from the **Q2 2025 Access Control Review**:\n\n- **Scope**: 342 active user accounts across 12 critical systems\n- **Result**: **98.5%** of accounts confirmed as appropriately provisioned\n- **Exceptions**: 5 accounts flagged for review (1.5%)\n  - 2 accounts with role changes not reflected in access levels\n  - 3 accounts for terminated employees with pending deprovisioning\n\nAll exceptions were remediated within the 15-day SLA. The review was conducted by the IT Security team and approved by the CISO on June 1, 2025.",
    citations: [mockCitations[2]],
    confidence: 0.85,
    confidenceLevel: "high",
    explanation: "Retrieved evidence document via full-text search matching on control ID and period. Single source with clear factual content.",
    retrievalMode: "fulltext",
    latencyMs: 890,
    timestamp: "2025-06-10T14:02:02Z",
  },
];

export const mockRecentQueries = [
  {
    id: "q_001",
    query: "What are the ISO 27001 requirements for risk assessment?",
    engagementName: "ISO 27001 ISMS Audit 2025",
    confidence: 0.91,
    timestamp: "2025-06-10T14:00:00Z",
  },
  {
    id: "q_002",
    query: "Show me the latest access review evidence for Q2 2025",
    engagementName: "ISO 27001 ISMS Audit 2025",
    confidence: 0.85,
    timestamp: "2025-06-10T14:02:00Z",
  },
  {
    id: "q_003",
    query: "List all change management controls and their testing status",
    engagementName: "SOX IT Controls Review",
    confidence: 0.78,
    timestamp: "2025-06-09T10:30:00Z",
  },
  {
    id: "q_004",
    query: "What GDPR articles apply to data processor agreements?",
    engagementName: "GDPR Compliance Assessment",
    confidence: 0.88,
    timestamp: "2025-06-08T15:45:00Z",
  },
  {
    id: "q_005",
    query: "Summarize prior year findings for vendor risk management",
    engagementName: "Vendor Risk Assessment Q1",
    confidence: 0.72,
    timestamp: "2025-06-07T09:15:00Z",
  },
];

export const mockDashboardStats = {
  totalEngagements: 5,
  activeEngagements: 2,
  documentsIndexed: 193,
  queriesThisWeek: 47,
};
