import type { Engagement } from "@/types/engagement";
import type { AuditDocument } from "@/types/document";
import type { ChatMessage, Citation } from "@/types/chat";

export const mockMatters: Engagement[] = [
  {
    id: "mat_001",
    name: "Acme Corp — Series C M&A Due Diligence",
    description: "Full legal due diligence for $420M acquisition of Acme Corp by Globex Industries",
    status: "active",
    entityName: "Globex Industries",
    entityId: "ent_002",
    periodStart: "2025-03-01",
    periodEnd: "2025-09-30",
    framework: "M&A / Corporate",
    members: [
      { id: "m1", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "lead_counsel" },
      { id: "m2", userId: "usr_003", name: "James Wilson", email: "auditor@audit.dev", role: "associate" },
    ],
    stats: { documentCount: 214, queryCount: 87, findingCount: 12, coveragePercent: 68 },
    createdAt: "2025-03-01T09:00:00Z",
    updatedAt: "2025-06-10T14:30:00Z",
    lastActivityAt: "2025-06-10T14:30:00Z",
  },
  {
    id: "mat_002",
    name: "TechCo v. InnovateCo — Patent Infringement",
    description: "Defense of patent infringement claim on ML inference engine technology",
    status: "active",
    entityName: "InnovateCo",
    entityId: "ent_003",
    periodStart: "2025-01-15",
    periodEnd: "2025-12-31",
    framework: "Litigation / IP",
    members: [
      { id: "m3", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "lead_counsel" },
      { id: "m4", userId: "usr_005", name: "David Kim", email: "david@audit.dev", role: "associate" },
    ],
    stats: { documentCount: 156, queryCount: 203, findingCount: 8, coveragePercent: 82 },
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-06-09T11:00:00Z",
    lastActivityAt: "2025-06-09T11:00:00Z",
  },
  {
    id: "mat_003",
    name: "Employment Agreement Templates Review",
    description: "Annual review and update of standard employment agreement templates for EU operations",
    status: "review",
    entityName: "Acme Corporation",
    entityId: "ent_001",
    periodStart: "2025-04-01",
    periodEnd: "2025-06-30",
    framework: "Employment / Labour",
    members: [
      { id: "m5", userId: "usr_003", name: "James Wilson", email: "auditor@audit.dev", role: "associate" },
    ],
    stats: { documentCount: 28, queryCount: 41, findingCount: 5, coveragePercent: 95 },
    createdAt: "2025-04-01T08:00:00Z",
    updatedAt: "2025-06-08T16:00:00Z",
    lastActivityAt: "2025-06-08T16:00:00Z",
  },
  {
    id: "mat_004",
    name: "SaaS Master Service Agreement — CloudVendor",
    description: "Negotiation and review of enterprise SaaS MSA with CloudVendor Inc.",
    status: "closed",
    entityName: "Acme Corporation",
    entityId: "ent_001",
    periodStart: "2025-01-01",
    periodEnd: "2025-03-31",
    framework: "Commercial / Contracts",
    members: [
      { id: "m6", userId: "usr_005", name: "David Kim", email: "david@audit.dev", role: "associate" },
    ],
    stats: { documentCount: 19, queryCount: 34, findingCount: 3, coveragePercent: 100 },
    createdAt: "2025-01-10T09:00:00Z",
    updatedAt: "2025-04-02T12:00:00Z",
    lastActivityAt: "2025-04-02T12:00:00Z",
  },
];

export const mockLegalDocuments: AuditDocument[] = [
  {
    id: "ldoc_001",
    title: "Acme Corp — Share Purchase Agreement (Draft v4)",
    docType: "policy",
    sourceSystem: "upload",
    confidentialityLevel: "confidential",
    engagementId: "mat_001",
    entityId: "ent_002",
    framework: "M&A / Corporate",
    version: 4,
    pageCount: 87,
    fileSize: 4200000,
    mimeType: "application/pdf",
    chunkCount: 312,
    createdAt: "2025-05-10T08:00:00Z",
    updatedAt: "2025-06-01T14:00:00Z",
  },
  {
    id: "ldoc_002",
    title: "TechCo Patent US10,234,567 — Claim Chart",
    docType: "evidence",
    sourceSystem: "upload",
    confidentialityLevel: "confidential",
    engagementId: "mat_002",
    entityId: "ent_003",
    framework: "Litigation / IP",
    version: 1,
    pageCount: 34,
    fileSize: 1800000,
    mimeType: "application/pdf",
    chunkCount: 98,
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "ldoc_003",
    title: "EU Standard Employment Contract Template v2025",
    docType: "policy",
    sourceSystem: "sharepoint",
    confidentialityLevel: "internal",
    engagementId: "mat_003",
    entityId: "ent_001",
    framework: "Employment / Labour",
    version: 2,
    pageCount: 22,
    fileSize: 980000,
    mimeType: "application/pdf",
    chunkCount: 64,
    createdAt: "2025-04-05T09:00:00Z",
    updatedAt: "2025-05-20T11:00:00Z",
  },
];

export const mockLegalCitations: Citation[] = [
  {
    id: "lcit_001",
    documentId: "ldoc_001",
    documentTitle: "Acme Corp — Share Purchase Agreement (Draft v4)",
    chunkId: "chunk_088",
    pageNumber: 31,
    sectionPath: "Clause 8.3 — Change of Control",
    snippet: "In the event of a Change of Control, all outstanding unvested options shall vest immediately and the acquirer shall assume all obligations under existing customer agreements unless otherwise agreed in writing.",
    score: 0.96,
    retrievalType: "hybrid",
  },
  {
    id: "lcit_002",
    documentId: "ldoc_002",
    documentTitle: "TechCo Patent US10,234,567 — Claim Chart",
    chunkId: "chunk_012",
    pageNumber: 5,
    sectionPath: "Claim 1 — Independent Claim",
    snippet: "A method for distributed inference comprising: receiving a model request; partitioning the model across N compute nodes; executing forward passes in parallel; and aggregating outputs via a weighted ensemble.",
    score: 0.91,
    retrievalType: "vector",
  },
  {
    id: "lcit_003",
    documentId: "ldoc_003",
    documentTitle: "EU Standard Employment Contract Template v2025",
    chunkId: "chunk_019",
    pageNumber: 8,
    sectionPath: "Section 5 — Termination",
    snippet: "Either party may terminate this agreement with 30 days written notice. In cases of gross misconduct, the employer may terminate with immediate effect subject to the requirements of applicable national labour law.",
    score: 0.88,
    retrievalType: "fulltext",
  },
];

export const mockLegalChatMessages: ChatMessage[] = [
  {
    id: "lmsg_001",
    role: "user",
    content: "What are the change-of-control provisions in the Acme SPA?",
    timestamp: "2025-06-10T10:00:00Z",
  },
  {
    id: "lmsg_002",
    role: "assistant",
    content: "Based on the **Share Purchase Agreement (Draft v4)**, the change-of-control provisions in Clause 8.3 include:\n\n1. **Accelerated Vesting** — All outstanding unvested options vest immediately upon a Change of Control event.\n\n2. **Assumption of Obligations** — The acquirer must assume all obligations under existing customer agreements unless otherwise agreed in writing.\n\n3. **Definition** — A \"Change of Control\" is defined as any transaction resulting in a third party acquiring more than 50% of the voting shares.\n\nNote: Clause 8.3 has been flagged for negotiation — the current draft does not include a carve-out for internal restructuring events.",
    citations: [mockLegalCitations[0]],
    confidence: 0.94,
    confidenceLevel: "high",
    explanation: "Retrieved directly from the SPA draft via hybrid search. High confidence — direct clause match.",
    retrievalMode: "hybrid",
    latencyMs: 1050,
    timestamp: "2025-06-10T10:00:02Z",
  },
];

export const mockLegalDashboardStats = {
  totalEngagements: 4,
  activeEngagements: 2,
  documentsIndexed: 417,
  queriesThisWeek: 62,
};
