import type { Engagement } from "@/types/engagement";
import type { AuditDocument } from "@/types/document";
import type { ChatMessage, Citation } from "@/types/chat";

export const mockPrograms: Engagement[] = [
  {
    id: "prg_001",
    name: "GDPR Compliance Program 2025",
    description: "Enterprise-wide GDPR compliance program covering all EU data processing activities",
    status: "active",
    entityName: "Acme Corporation",
    entityId: "ent_001",
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    framework: "GDPR",
    members: [
      { id: "m1", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "compliance_lead" },
      { id: "m2", userId: "usr_003", name: "James Wilson", email: "auditor@audit.dev", role: "analyst" },
    ],
    stats: { documentCount: 63, queryCount: 142, findingCount: 9, coveragePercent: 74 },
    createdAt: "2025-01-05T09:00:00Z",
    updatedAt: "2025-06-10T14:30:00Z",
    lastActivityAt: "2025-06-10T14:30:00Z",
  },
  {
    id: "prg_002",
    name: "SOC 2 Type II Certification",
    description: "Annual SOC 2 Type II audit preparation covering Security, Availability, and Confidentiality trust criteria",
    status: "active",
    entityName: "Globex Industries",
    entityId: "ent_002",
    periodStart: "2025-01-01",
    periodEnd: "2025-12-31",
    framework: "SOC 2",
    members: [
      { id: "m3", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "compliance_lead" },
      { id: "m4", userId: "usr_005", name: "David Kim", email: "david@audit.dev", role: "analyst" },
    ],
    stats: { documentCount: 108, queryCount: 219, findingCount: 6, coveragePercent: 88 },
    createdAt: "2025-01-10T09:00:00Z",
    updatedAt: "2025-06-09T11:00:00Z",
    lastActivityAt: "2025-06-09T11:00:00Z",
  },
  {
    id: "prg_003",
    name: "AML/KYC Annual Review",
    description: "Annual review of Anti-Money Laundering and Know Your Customer procedures",
    status: "review",
    entityName: "Globex Industries",
    entityId: "ent_002",
    periodStart: "2025-01-01",
    periodEnd: "2025-06-30",
    framework: "AML/KYC",
    members: [
      { id: "m5", userId: "usr_003", name: "James Wilson", email: "auditor@audit.dev", role: "analyst" },
    ],
    stats: { documentCount: 44, queryCount: 78, findingCount: 4, coveragePercent: 91 },
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-06-08T16:00:00Z",
    lastActivityAt: "2025-06-08T16:00:00Z",
  },
  {
    id: "prg_004",
    name: "PCI-DSS v4.0 Gap Assessment",
    description: "Gap assessment against PCI-DSS v4.0 requirements for cardholder data environment",
    status: "planning",
    entityName: "Acme Corporation",
    entityId: "ent_001",
    periodStart: "2025-07-01",
    periodEnd: "2025-12-31",
    framework: "PCI-DSS",
    members: [
      { id: "m6", userId: "usr_002", name: "Sarah Chen", email: "manager@audit.dev", role: "compliance_lead" },
    ],
    stats: { documentCount: 7, queryCount: 0, findingCount: 0, coveragePercent: 0 },
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2025-06-05T10:00:00Z",
    lastActivityAt: "2025-06-05T10:00:00Z",
  },
];

export const mockComplianceDocuments: AuditDocument[] = [
  {
    id: "cdoc_001",
    title: "GDPR Data Processing Register v3.1",
    docType: "policy",
    sourceSystem: "upload",
    confidentialityLevel: "confidential",
    engagementId: "prg_001",
    entityId: "ent_001",
    framework: "GDPR",
    version: 3,
    pageCount: 48,
    fileSize: 2100000,
    mimeType: "application/pdf",
    chunkCount: 164,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-05-15T14:00:00Z",
  },
  {
    id: "cdoc_002",
    title: "SOC 2 Security Policy — Globex Industries",
    docType: "policy",
    sourceSystem: "sharepoint",
    confidentialityLevel: "internal",
    engagementId: "prg_002",
    entityId: "ent_002",
    framework: "SOC 2",
    version: 2,
    pageCount: 36,
    fileSize: 1650000,
    mimeType: "application/pdf",
    chunkCount: 118,
    createdAt: "2025-02-10T10:00:00Z",
    updatedAt: "2025-04-20T09:00:00Z",
  },
  {
    id: "cdoc_003",
    title: "AML Customer Due Diligence Procedure",
    docType: "policy",
    sourceSystem: "confluence",
    confidentialityLevel: "confidential",
    engagementId: "prg_003",
    entityId: "ent_002",
    framework: "AML/KYC",
    version: 1,
    pageCount: 24,
    fileSize: 980000,
    mimeType: "application/pdf",
    chunkCount: 72,
    createdAt: "2025-02-15T11:00:00Z",
    updatedAt: "2025-05-10T09:00:00Z",
  },
];

export const mockComplianceCitations: Citation[] = [
  {
    id: "ccit_001",
    documentId: "cdoc_001",
    documentTitle: "GDPR Data Processing Register v3.1",
    chunkId: "chunk_041",
    pageNumber: 18,
    sectionPath: "Section 4 — Data Breach Notification",
    snippet: "In the event of a personal data breach, the controller shall notify the competent supervisory authority within 72 hours of becoming aware of the breach, unless the breach is unlikely to result in a risk to the rights and freedoms of natural persons.",
    score: 0.95,
    retrievalType: "hybrid",
  },
  {
    id: "ccit_002",
    documentId: "cdoc_002",
    documentTitle: "SOC 2 Security Policy — Globex Industries",
    chunkId: "chunk_027",
    pageNumber: 12,
    sectionPath: "CC6.1 — Logical and Physical Access Controls",
    snippet: "Access to production systems is restricted to authorized personnel only. Multi-factor authentication is required for all privileged access. Access reviews are conducted quarterly by system owners.",
    score: 0.89,
    retrievalType: "vector",
  },
  {
    id: "ccit_003",
    documentId: "cdoc_003",
    documentTitle: "AML Customer Due Diligence Procedure",
    chunkId: "chunk_008",
    pageNumber: 4,
    sectionPath: "Section 2.3 — Enhanced Due Diligence",
    snippet: "Enhanced Due Diligence (EDD) is required for all high-risk customers including Politically Exposed Persons (PEPs), customers from high-risk jurisdictions, and transactions exceeding €50,000.",
    score: 0.87,
    retrievalType: "fulltext",
  },
];

export const mockComplianceChatMessages: ChatMessage[] = [
  {
    id: "cmsg_001",
    role: "user",
    content: "What are our GDPR breach notification obligations?",
    timestamp: "2025-06-10T11:00:00Z",
  },
  {
    id: "cmsg_002",
    role: "assistant",
    content: "Based on your **GDPR Data Processing Register (v3.1)** and GDPR Article 33, your breach notification obligations are:\n\n1. **72-Hour Rule** — Notify the competent supervisory authority within 72 hours of becoming aware of a personal data breach.\n\n2. **Risk Threshold** — Notification is required unless the breach is *unlikely* to result in a risk to the rights and freedoms of natural persons.\n\n3. **Data Subject Notification** — If the breach is likely to result in *high risk*, affected individuals must also be notified without undue delay (Article 34).\n\n4. **Documentation** — All breaches must be documented in your breach register, regardless of whether notification is required.\n\n**Current gap identified**: Your internal procedure does not define a clear escalation path for the 72-hour notification window. This is flagged as Obligation OBL-007.",
    citations: [mockComplianceCitations[0]],
    confidence: 0.93,
    confidenceLevel: "high",
    explanation: "Retrieved from internal data processing register and cross-referenced with GDPR Article 33 via deep research.",
    retrievalMode: "hybrid",
    latencyMs: 1380,
    timestamp: "2025-06-10T11:00:03Z",
  },
];

export const mockComplianceDashboardStats = {
  totalEngagements: 4,
  activeEngagements: 2,
  documentsIndexed: 222,
  queriesThisWeek: 53,
};
