import type { Requirement, Control, RequirementControlMapping } from "@/types/requirement";
import type { EvidencePack, EvidenceItem } from "@/types/evidence";
import type { Workpaper } from "@/types/workpaper";
import type { Finding } from "@/types/finding";

// ── Requirements (ISO 27001 engagement) ──────────────────────────────
export const mockRequirements: Requirement[] = [
  {
    id: "req_001",
    engagementId: "eng_001",
    clauseId: "A.5.1",
    title: "Information Security Policies",
    description: "A set of policies for information security shall be defined, approved by management, published and communicated to employees and relevant external parties.",
    framework: "ISO 27001:2022",
    category: "Organizational Controls",
    status: "completed",
    controlIds: ["ctrl_001", "ctrl_002"],
    evidenceCount: 3,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-05-10T10:00:00Z",
  },
  {
    id: "req_002",
    engagementId: "eng_001",
    clauseId: "A.5.2",
    title: "Information Security Roles and Responsibilities",
    description: "Information security roles and responsibilities shall be defined and allocated.",
    framework: "ISO 27001:2022",
    category: "Organizational Controls",
    status: "tested",
    controlIds: ["ctrl_003"],
    evidenceCount: 2,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-05-12T11:00:00Z",
  },
  {
    id: "req_003",
    engagementId: "eng_001",
    clauseId: "A.6.1",
    title: "Screening",
    description: "Background verification checks on all candidates for employment shall be carried out prior to joining the organization.",
    framework: "ISO 27001:2022",
    category: "People Controls",
    status: "in_progress",
    controlIds: ["ctrl_004"],
    evidenceCount: 1,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "req_004",
    engagementId: "eng_001",
    clauseId: "A.8.1",
    title: "User Endpoint Devices",
    description: "Information stored on, processed by or accessible via user endpoint devices shall be protected.",
    framework: "ISO 27001:2022",
    category: "Technological Controls",
    status: "in_progress",
    controlIds: ["ctrl_005", "ctrl_006"],
    evidenceCount: 2,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-06-03T14:00:00Z",
  },
  {
    id: "req_005",
    engagementId: "eng_001",
    clauseId: "A.8.2",
    title: "Privileged Access Rights",
    description: "The allocation and use of privileged access rights shall be restricted and managed.",
    framework: "ISO 27001:2022",
    category: "Technological Controls",
    status: "tested",
    controlIds: ["ctrl_007"],
    evidenceCount: 4,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-06-05T16:00:00Z",
  },
  {
    id: "req_006",
    engagementId: "eng_001",
    clauseId: "A.8.9",
    title: "Configuration Management",
    description: "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.",
    framework: "ISO 27001:2022",
    category: "Technological Controls",
    status: "not_started",
    controlIds: [],
    evidenceCount: 0,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-01-20T08:00:00Z",
  },
  {
    id: "req_007",
    engagementId: "eng_001",
    clauseId: "A.8.16",
    title: "Monitoring Activities",
    description: "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken.",
    framework: "ISO 27001:2022",
    category: "Technological Controls",
    status: "not_started",
    controlIds: ["ctrl_008"],
    evidenceCount: 0,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-01-20T08:00:00Z",
  },
  {
    id: "req_008",
    engagementId: "eng_001",
    clauseId: "A.5.23",
    title: "Information Security for Use of Cloud Services",
    description: "Processes for acquisition, use, management and exit from cloud services shall be established.",
    framework: "ISO 27001:2022",
    category: "Organizational Controls",
    status: "in_progress",
    controlIds: ["ctrl_009"],
    evidenceCount: 1,
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-06-02T10:00:00Z",
  },
];

// ── Controls ─────────────────────────────────────────────────────────
export const mockControls: Control[] = [
  {
    id: "ctrl_001",
    controlId: "IS-POL-01",
    engagementId: "eng_001",
    title: "Information Security Policy Maintenance",
    description: "Information security policy is reviewed and approved by management annually.",
    category: "Policy",
    owner: "CISO Office",
    frequency: "Annual",
    effectiveness: "effective",
    testingStatus: "completed",
    requirementIds: ["req_001"],
    evidenceIds: ["doc_002"],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-05-10T10:00:00Z",
  },
  {
    id: "ctrl_002",
    controlId: "IS-POL-02",
    engagementId: "eng_001",
    title: "Policy Communication and Awareness",
    description: "Security policies are communicated to all employees and relevant third parties.",
    category: "Policy",
    owner: "HR / InfoSec",
    frequency: "Ongoing",
    effectiveness: "effective",
    testingStatus: "completed",
    requirementIds: ["req_001"],
    evidenceIds: [],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-05-10T10:00:00Z",
  },
  {
    id: "ctrl_003",
    controlId: "IS-ORG-01",
    engagementId: "eng_001",
    title: "Security Roles Assignment",
    description: "Information security roles and responsibilities are documented in job descriptions and RACI matrices.",
    category: "Organization",
    owner: "CISO Office",
    frequency: "Annual",
    effectiveness: "effective",
    testingStatus: "completed",
    requirementIds: ["req_002"],
    evidenceIds: [],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-05-12T11:00:00Z",
  },
  {
    id: "ctrl_004",
    controlId: "HR-SCR-01",
    engagementId: "eng_001",
    title: "Pre-Employment Background Checks",
    description: "Background verification checks are performed for all new hires prior to start date.",
    category: "People",
    owner: "Human Resources",
    frequency: "Per hire",
    effectiveness: "partially_effective",
    testingStatus: "in_progress",
    requirementIds: ["req_003"],
    evidenceIds: [],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "ctrl_005",
    controlId: "EP-MDM-01",
    engagementId: "eng_001",
    title: "MDM Enrollment and Configuration",
    description: "All corporate endpoint devices are enrolled in MDM with security baseline configuration.",
    category: "Technology",
    owner: "IT Operations",
    frequency: "Ongoing",
    effectiveness: "effective",
    testingStatus: "completed",
    requirementIds: ["req_004"],
    evidenceIds: [],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-06-03T14:00:00Z",
  },
  {
    id: "ctrl_006",
    controlId: "EP-ENC-01",
    engagementId: "eng_001",
    title: "Endpoint Encryption",
    description: "Full disk encryption is enforced on all endpoint devices.",
    category: "Technology",
    owner: "IT Operations",
    frequency: "Ongoing",
    effectiveness: "effective",
    testingStatus: "in_progress",
    requirementIds: ["req_004"],
    evidenceIds: [],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-06-03T14:00:00Z",
  },
  {
    id: "ctrl_007",
    controlId: "AC-01",
    engagementId: "eng_001",
    title: "Privileged Access Management",
    description: "Privileged access is restricted, reviewed quarterly, and requires documented justification.",
    category: "Access Control",
    owner: "IT Security",
    frequency: "Quarterly",
    effectiveness: "effective",
    testingStatus: "completed",
    requirementIds: ["req_005"],
    evidenceIds: ["doc_003"],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-06-05T16:00:00Z",
  },
  {
    id: "ctrl_008",
    controlId: "MON-01",
    engagementId: "eng_001",
    title: "SIEM Monitoring",
    description: "SIEM system monitors network, system and application logs for anomalous behaviour.",
    category: "Monitoring",
    owner: "SOC",
    frequency: "Continuous",
    effectiveness: "not_tested",
    testingStatus: "pending",
    requirementIds: ["req_007"],
    evidenceIds: [],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-01-22T10:00:00Z",
  },
  {
    id: "ctrl_009",
    controlId: "CLD-01",
    engagementId: "eng_001",
    title: "Cloud Security Baseline",
    description: "Cloud services are assessed against security requirements before procurement and monitored during use.",
    category: "Cloud",
    owner: "Cloud Engineering",
    frequency: "Per service",
    effectiveness: "partially_effective",
    testingStatus: "in_progress",
    requirementIds: ["req_008"],
    evidenceIds: [],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-06-02T10:00:00Z",
  },
];

// ── Requirement ↔ Control Mappings ───────────────────────────────────
export const mockMappings: RequirementControlMapping[] = [
  { id: "map_001", requirementId: "req_001", controlId: "ctrl_001", status: "mapped", lastVerified: "2025-05-10T10:00:00Z" },
  { id: "map_002", requirementId: "req_001", controlId: "ctrl_002", status: "mapped", lastVerified: "2025-05-10T10:00:00Z" },
  { id: "map_003", requirementId: "req_002", controlId: "ctrl_003", status: "mapped", lastVerified: "2025-05-12T11:00:00Z" },
  { id: "map_004", requirementId: "req_003", controlId: "ctrl_004", status: "partial", notes: "Background check process documented but not all hires covered" },
  { id: "map_005", requirementId: "req_004", controlId: "ctrl_005", status: "mapped", lastVerified: "2025-06-03T14:00:00Z" },
  { id: "map_006", requirementId: "req_004", controlId: "ctrl_006", status: "mapped", lastVerified: "2025-06-03T14:00:00Z" },
  { id: "map_007", requirementId: "req_005", controlId: "ctrl_007", status: "mapped", lastVerified: "2025-06-05T16:00:00Z" },
  { id: "map_008", requirementId: "req_006", controlId: "ctrl_008", status: "gap", notes: "Configuration management control not yet defined" },
  { id: "map_009", requirementId: "req_007", controlId: "ctrl_008", status: "partial", notes: "SIEM in place but testing pending" },
  { id: "map_010", requirementId: "req_008", controlId: "ctrl_009", status: "partial", notes: "Cloud security baseline defined but not yet fully enforced" },
];

// ── Evidence Packs ───────────────────────────────────────────────────
export const mockEvidencePacks: EvidencePack[] = [
  {
    id: "ep_001",
    engagementId: "eng_001",
    name: "Privileged Access Review - Q2 2025",
    description: "Evidence pack for AC-01 privileged access management control",
    controlId: "AC-01",
    controlTitle: "Privileged Access Management",
    status: "approved",
    items: [
      {
        id: "ei_001",
        documentId: "doc_003",
        documentTitle: "Access Control Evidence - Q2 2025",
        docType: "evidence",
        controlId: "AC-01",
        relevanceScore: 0.94,
        snippet: "Quarterly access review covered 342 active user accounts across 12 critical systems.",
        pageNumber: 3,
        addedAt: "2025-06-02T10:00:00Z",
        addedBy: "James Wilson",
      },
      {
        id: "ei_002",
        documentId: "doc_002",
        documentTitle: "Acme Corp - Information Security Policy v3.2",
        docType: "policy",
        controlId: "AC-01",
        relevanceScore: 0.82,
        snippet: "Privileged accounts are reviewed quarterly by the IT Security team with CISO approval.",
        pageNumber: 12,
        addedAt: "2025-06-02T10:05:00Z",
        addedBy: "James Wilson",
      },
    ],
    createdBy: "James Wilson",
    createdAt: "2025-06-02T09:50:00Z",
    updatedAt: "2025-06-05T16:00:00Z",
  },
  {
    id: "ep_002",
    engagementId: "eng_001",
    name: "Information Security Policy Review",
    description: "Evidence for IS-POL-01 policy maintenance control",
    controlId: "IS-POL-01",
    controlTitle: "Information Security Policy Maintenance",
    status: "in_review",
    items: [
      {
        id: "ei_003",
        documentId: "doc_002",
        documentTitle: "Acme Corp - Information Security Policy v3.2",
        docType: "policy",
        relevanceScore: 0.96,
        snippet: "Policy approved by CEO and CISO on March 15, 2025. Version 3.2.",
        pageNumber: 1,
        addedAt: "2025-05-10T10:00:00Z",
        addedBy: "Sarah Chen",
      },
    ],
    createdBy: "Sarah Chen",
    createdAt: "2025-05-10T09:30:00Z",
    updatedAt: "2025-05-10T10:15:00Z",
  },
  {
    id: "ep_003",
    engagementId: "eng_001",
    name: "Endpoint Security Controls",
    description: "Evidence for EP-MDM-01 and EP-ENC-01 controls",
    controlId: "EP-MDM-01",
    controlTitle: "MDM Enrollment and Configuration",
    status: "draft",
    items: [],
    createdBy: "Maria Garcia",
    createdAt: "2025-06-04T08:00:00Z",
    updatedAt: "2025-06-04T08:00:00Z",
  },
];

// ── Workpapers ───────────────────────────────────────────────────────
export const mockWorkpapers: Workpaper[] = [
  {
    id: "wp_001",
    engagementId: "eng_001",
    title: "Privileged Access Management - Test of Controls",
    type: "test_of_controls",
    status: "reviewed",
    controlId: "AC-01",
    controlTitle: "Privileged Access Management",
    preparedBy: "James Wilson",
    reviewedBy: "Sarah Chen",
    sections: [
      {
        id: "sec_001",
        label: "Criteria",
        content: "Per ISO 27001:2022 Clause A.8.2, the allocation and use of privileged access rights shall be restricted and managed. Acme Corp's Information Security Policy (v3.2, Section 5.3) requires quarterly reviews of privileged accounts with documented justification.",
        citations: ["cit_001", "cit_002"],
      },
      {
        id: "sec_002",
        label: "Condition",
        content: "Reviewed Q2 2025 privileged access review documentation. 12 privileged accounts identified across critical systems. All accounts had documented business justification. Quarterly review completed on schedule.",
        citations: ["cit_003"],
      },
      {
        id: "sec_003",
        label: "Testing Procedures",
        content: "1. Obtained the Q2 2025 privileged access review report.\n2. Verified review was performed within the quarterly schedule.\n3. Confirmed all 12 privileged accounts had documented justification.\n4. Verified CISO sign-off on the review.\n5. Tested a sample of 5 accounts for appropriate access levels.",
      },
      {
        id: "sec_004",
        label: "Results",
        content: "No exceptions noted. All privileged accounts were appropriately provisioned with valid business justification. The review was completed on schedule with proper management approval.",
      },
    ],
    createdAt: "2025-06-06T09:00:00Z",
    updatedAt: "2025-06-08T14:00:00Z",
  },
  {
    id: "wp_002",
    engagementId: "eng_001",
    title: "Information Security Policy - Walkthrough",
    type: "walkthrough",
    status: "draft",
    controlId: "IS-POL-01",
    controlTitle: "Information Security Policy Maintenance",
    preparedBy: "Maria Garcia",
    sections: [
      {
        id: "sec_005",
        label: "Criteria",
        content: "ISO 27001:2022 Clause A.5.1 requires that information security policies are defined, approved, published, and communicated.",
      },
      {
        id: "sec_006",
        label: "Condition",
        content: "",
      },
      {
        id: "sec_007",
        label: "Testing Procedures",
        content: "",
      },
      {
        id: "sec_008",
        label: "Results",
        content: "",
      },
    ],
    createdAt: "2025-06-07T10:00:00Z",
    updatedAt: "2025-06-07T10:00:00Z",
  },
  {
    id: "wp_003",
    engagementId: "eng_001",
    title: "Cloud Security Assessment Memo",
    type: "memo",
    status: "draft",
    controlId: "CLD-01",
    controlTitle: "Cloud Security Baseline",
    preparedBy: "James Wilson",
    sections: [
      {
        id: "sec_009",
        label: "Background",
        content: "Acme Corp utilizes multiple cloud services including AWS, Azure, and SaaS applications. This memo documents the assessment of cloud security controls per ISO 27001:2022 Clause A.5.23.",
      },
      {
        id: "sec_010",
        label: "Analysis",
        content: "",
      },
      {
        id: "sec_011",
        label: "Conclusion",
        content: "",
      },
    ],
    createdAt: "2025-06-08T11:00:00Z",
    updatedAt: "2025-06-08T11:00:00Z",
  },
];

// ── Findings ─────────────────────────────────────────────────────────
export const mockFindings: Finding[] = [
  {
    id: "fnd_001",
    engagementId: "eng_001",
    title: "Incomplete Background Verification for Contract Staff",
    severity: "medium",
    status: "accepted",
    controlId: "HR-SCR-01",
    controlTitle: "Pre-Employment Background Checks",
    criteria: "Per ISO 27001:2022 Clause A.6.1, background verification checks shall be carried out on all candidates for employment prior to joining the organization. Acme Corp's HR Policy (Section 3.2) extends this requirement to all contract staff.",
    condition: "During testing of 25 new hires in Q1-Q2 2025, background checks were completed for all 18 full-time employees. However, 3 of 7 contract staff (43%) did not have background checks completed prior to their start date.",
    cause: "The HR onboarding workflow does not automatically trigger the background check process for contract staff engaged through staffing agencies. The process relies on manual initiation by the hiring manager.",
    effect: "Individuals without proper background verification may gain access to sensitive information and systems, increasing the risk of insider threats, data breaches, or regulatory non-compliance.",
    recommendation: "1. Extend the automated onboarding workflow to include all engagement types (FTE and contract).\n2. Implement a system control that blocks system access provisioning until background check clearance is confirmed.\n3. Conduct retrospective background checks for the 3 identified contract staff.",
    managementResponse: "Agreed. HR will update the onboarding workflow by end of Q3 2025. IT will implement the access provisioning gate by end of Q2 2025.",
    targetDate: "2025-09-30",
    citationIds: ["cit_001"],
    createdBy: "James Wilson",
    createdAt: "2025-06-05T10:00:00Z",
    updatedAt: "2025-06-08T14:00:00Z",
  },
  {
    id: "fnd_002",
    engagementId: "eng_001",
    title: "Cloud Service Security Assessment Not Formalized",
    severity: "high",
    status: "in_review",
    controlId: "CLD-01",
    controlTitle: "Cloud Security Baseline",
    criteria: "ISO 27001:2022 Clause A.5.23 requires that processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization's information security requirements.",
    condition: "Review of 8 cloud services in use revealed that only 3 (37.5%) had a documented security assessment completed prior to procurement. The remaining 5 services were adopted without formal security review.",
    cause: "No formal cloud service onboarding process exists. Individual departments can procure SaaS solutions through corporate credit cards without InfoSec review.",
    effect: "Unapproved cloud services may not meet security requirements, potentially exposing sensitive data to unauthorized access, violating data residency requirements, or creating shadow IT risks.",
    recommendation: "1. Establish a mandatory cloud security assessment process for all new cloud services.\n2. Create a pre-approved cloud service catalog.\n3. Implement procurement controls requiring InfoSec sign-off for all cloud service subscriptions.\n4. Conduct retrospective security assessments for the 5 unreviewed services.",
    citationIds: ["cit_002"],
    createdBy: "Maria Garcia",
    createdAt: "2025-06-06T11:00:00Z",
    updatedAt: "2025-06-09T09:00:00Z",
  },
  {
    id: "fnd_003",
    engagementId: "eng_001",
    title: "SIEM Alert Tuning Documentation Missing",
    severity: "low",
    status: "draft",
    controlId: "MON-01",
    controlTitle: "SIEM Monitoring",
    criteria: "ISO 27001:2022 Clause A.8.16 requires monitoring of networks, systems and applications for anomalous behaviour with appropriate actions taken.",
    condition: "The SIEM system is operational and processing logs. However, the alert tuning rationale and false-positive reduction process are not documented.",
    cause: "The SOC team manages alert tuning as part of their operational workflow but has not formalized the documentation per audit requirements.",
    effect: "Without documented alert tuning rationale, it is difficult to verify that monitoring coverage is adequate and that alert thresholds are appropriate for the threat landscape.",
    recommendation: "Document the current SIEM alert rules, tuning rationale, and false-positive management process. Establish a quarterly review cycle for alert effectiveness.",
    citationIds: [],
    createdBy: "James Wilson",
    createdAt: "2025-06-08T15:00:00Z",
    updatedAt: "2025-06-08T15:00:00Z",
  },
];

// ── Candidate evidence for evidence finder ───────────────────────────
export const mockEvidenceCandidates: EvidenceItem[] = [
  {
    id: "ec_001",
    documentId: "doc_003",
    documentTitle: "Access Control Evidence - Q2 2025",
    docType: "evidence",
    controlId: "AC-01",
    relevanceScore: 0.94,
    snippet: "Quarterly access review covered 342 active user accounts across 12 critical systems. 98.5% compliance rate.",
    pageNumber: 3,
    addedAt: "2025-06-02T09:00:00Z",
    addedBy: "system",
  },
  {
    id: "ec_002",
    documentId: "doc_002",
    documentTitle: "Acme Corp - Information Security Policy v3.2",
    docType: "policy",
    controlId: "IS-POL-01",
    relevanceScore: 0.91,
    snippet: "Information security policy approved by CEO on March 15, 2025. Annual review cycle established.",
    pageNumber: 1,
    addedAt: "2025-06-02T09:00:00Z",
    addedBy: "system",
  },
  {
    id: "ec_003",
    documentId: "doc_001",
    documentTitle: "ISO 27001:2022 Standard Full Text",
    docType: "standard",
    relevanceScore: 0.88,
    snippet: "Clause A.8.2: The allocation and use of privileged access rights shall be restricted and managed.",
    pageNumber: 22,
    addedAt: "2025-06-02T09:00:00Z",
    addedBy: "system",
  },
  {
    id: "ec_004",
    documentId: "doc_002",
    documentTitle: "Acme Corp - Information Security Policy v3.2",
    docType: "policy",
    controlId: "HR-SCR-01",
    relevanceScore: 0.79,
    snippet: "All new employees and contractors shall undergo background verification checks prior to start date.",
    pageNumber: 8,
    addedAt: "2025-06-02T09:00:00Z",
    addedBy: "system",
  },
  {
    id: "ec_005",
    documentId: "doc_001",
    documentTitle: "ISO 27001:2022 Standard Full Text",
    docType: "standard",
    relevanceScore: 0.85,
    snippet: "Clause A.5.23: Processes for acquisition, use, management and exit from cloud services shall be established.",
    pageNumber: 18,
    addedAt: "2025-06-02T09:00:00Z",
    addedBy: "system",
  },
];
