import type {
  ManagedUser,
  AuditTrailEntry,
  QueryLogEntry,
  ServiceHealth,
  SystemMetric,
  ModelCard,
  KillSwitchState,
  GoalDriftAlert,
  ApprovalRequest,
} from "@/types/admin";

// ── Users ────────────────────────────────────────────────────────────
export const mockManagedUsers: ManagedUser[] = [
  {
    id: "usr_001",
    name: "Alex Thompson",
    email: "admin@audit.dev",
    role: "admin",
    status: "active",
    department: "IT Audit",
    lastLoginAt: "2025-06-10T14:00:00Z",
    engagementCount: 5,
    createdAt: "2024-06-01T08:00:00Z",
    updatedAt: "2025-06-10T14:00:00Z",
  },
  {
    id: "usr_002",
    name: "Sarah Chen",
    email: "manager@audit.dev",
    role: "audit_manager",
    status: "active",
    department: "IT Audit",
    lastLoginAt: "2025-06-10T11:00:00Z",
    engagementCount: 3,
    createdAt: "2024-08-15T09:00:00Z",
    updatedAt: "2025-06-10T11:00:00Z",
  },
  {
    id: "usr_003",
    name: "James Wilson",
    email: "auditor@audit.dev",
    role: "auditor",
    status: "active",
    department: "IT Audit",
    lastLoginAt: "2025-06-10T09:30:00Z",
    engagementCount: 2,
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: "2025-06-10T09:30:00Z",
  },
  {
    id: "usr_004",
    name: "Maria Garcia",
    email: "maria@audit.dev",
    role: "auditor",
    status: "active",
    department: "IT Audit",
    lastLoginAt: "2025-06-09T16:00:00Z",
    engagementCount: 1,
    createdAt: "2025-01-15T08:00:00Z",
    updatedAt: "2025-06-09T16:00:00Z",
  },
  {
    id: "usr_005",
    name: "David Kim",
    email: "david@audit.dev",
    role: "auditor",
    status: "active",
    department: "Financial Audit",
    lastLoginAt: "2025-06-09T10:00:00Z",
    engagementCount: 2,
    createdAt: "2025-02-01T09:00:00Z",
    updatedAt: "2025-06-09T10:00:00Z",
  },
  {
    id: "usr_006",
    name: "Emily Roberts",
    email: "emily@audit.dev",
    role: "viewer",
    status: "inactive",
    department: "Compliance",
    engagementCount: 0,
    createdAt: "2025-03-10T11:00:00Z",
    updatedAt: "2025-05-01T08:00:00Z",
  },
  {
    id: "usr_007",
    name: "Michael Brown",
    email: "michael@audit.dev",
    role: "auditor",
    status: "locked",
    department: "IT Audit",
    lastLoginAt: "2025-04-20T14:00:00Z",
    engagementCount: 1,
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-04-20T14:00:00Z",
  },
];

// ── Audit Trail ──────────────────────────────────────────────────────
export const mockAuditTrail: AuditTrailEntry[] = [
  {
    id: "at_001",
    eventType: "query",
    userId: "usr_003",
    userName: "James Wilson",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    description: "Queried: 'What are the ISO 27001 requirements for risk assessment?'",
    timestamp: "2025-06-10T14:00:00Z",
  },
  {
    id: "at_002",
    eventType: "query",
    userId: "usr_003",
    userName: "James Wilson",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    description: "Queried: 'Show me the latest access review evidence for Q2 2025'",
    timestamp: "2025-06-10T14:02:00Z",
  },
  {
    id: "at_003",
    eventType: "document_upload",
    userId: "usr_004",
    userName: "Maria Garcia",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    description: "Uploaded document: 'Access Control Evidence - Q2 2025'",
    timestamp: "2025-06-02T09:00:00Z",
  },
  {
    id: "at_004",
    eventType: "finding_create",
    userId: "usr_003",
    userName: "James Wilson",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    description: "Created finding: 'Incomplete Background Verification for Contract Staff'",
    timestamp: "2025-06-05T10:00:00Z",
  },
  {
    id: "at_005",
    eventType: "workpaper_update",
    userId: "usr_002",
    userName: "Sarah Chen",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    description: "Reviewed workpaper: 'Privileged Access Management - Test of Controls'",
    timestamp: "2025-06-08T14:00:00Z",
  },
  {
    id: "at_006",
    eventType: "evidence_pack_export",
    userId: "usr_003",
    userName: "James Wilson",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    description: "Exported evidence pack: 'Privileged Access Review - Q2 2025'",
    timestamp: "2025-06-05T17:00:00Z",
  },
  {
    id: "at_007",
    eventType: "user_login",
    userId: "usr_001",
    userName: "Alex Thompson",
    description: "User logged in via SSO",
    ipAddress: "192.168.1.100",
    timestamp: "2025-06-10T08:00:00Z",
  },
  {
    id: "at_008",
    eventType: "engagement_create",
    userId: "usr_002",
    userName: "Sarah Chen",
    engagementId: "eng_005",
    engagementName: "Change Management ITGC",
    description: "Created engagement: 'Change Management ITGC'",
    timestamp: "2025-06-01T09:00:00Z",
  },
  {
    id: "at_009",
    eventType: "permission_change",
    userId: "usr_001",
    userName: "Alex Thompson",
    description: "Changed role for Emily Roberts from 'auditor' to 'viewer'",
    timestamp: "2025-05-01T08:00:00Z",
  },
  {
    id: "at_010",
    eventType: "engagement_update",
    userId: "usr_002",
    userName: "Sarah Chen",
    engagementId: "eng_004",
    engagementName: "Vendor Risk Assessment Q1",
    description: "Closed engagement: 'Vendor Risk Assessment Q1'",
    timestamp: "2025-04-15T12:00:00Z",
  },
];

// ── Query Logs with Agent Steps ──────────────────────────────────────
export const mockQueryLogs: QueryLogEntry[] = [
  {
    id: "ql_001",
    userId: "usr_003",
    userName: "James Wilson",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    query: "What are the ISO 27001 requirements for risk assessment?",
    runId: "run_abc123",
    retrievalMode: "hybrid",
    confidence: 0.91,
    latencyMs: 1240,
    citationCount: 2,
    agentSteps: [
      { node: "policyCheck", status: "success", durationMs: 45, detail: "User authorized for eng_001" },
      { node: "queryRouter", status: "success", durationMs: 120, detail: "Routed to hybrid mode" },
      { node: "retrieve", status: "success", durationMs: 680, detail: "Retrieved 8 chunks, reranked to top 3" },
      { node: "generate", status: "success", durationMs: 350, detail: "Generated answer with 2 citations" },
      { node: "guardrails", status: "success", durationMs: 25, detail: "Passed all guardrails" },
      { node: "logAuditTrail", status: "success", durationMs: 20, detail: "Logged to audit trail" },
    ],
    timestamp: "2025-06-10T14:00:00Z",
  },
  {
    id: "ql_002",
    userId: "usr_003",
    userName: "James Wilson",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    query: "Show me the latest access review evidence for Q2 2025",
    runId: "run_def456",
    retrievalMode: "fulltext",
    confidence: 0.85,
    latencyMs: 890,
    citationCount: 1,
    agentSteps: [
      { node: "policyCheck", status: "success", durationMs: 38, detail: "User authorized for eng_001" },
      { node: "queryRouter", status: "success", durationMs: 95, detail: "Routed to fulltext mode" },
      { node: "retrieve", status: "success", durationMs: 420, detail: "Retrieved 5 chunks, reranked to top 2" },
      { node: "generate", status: "success", durationMs: 310, detail: "Generated answer with 1 citation" },
      { node: "guardrails", status: "success", durationMs: 12, detail: "Passed all guardrails" },
      { node: "logAuditTrail", status: "success", durationMs: 15, detail: "Logged to audit trail" },
    ],
    timestamp: "2025-06-10T14:02:00Z",
  },
  {
    id: "ql_003",
    userId: "usr_005",
    userName: "David Kim",
    engagementId: "eng_002",
    engagementName: "SOX IT Controls Review",
    query: "List all change management controls and their testing status",
    runId: "run_ghi789",
    retrievalMode: "hybrid",
    confidence: 0.78,
    latencyMs: 1560,
    citationCount: 3,
    agentSteps: [
      { node: "policyCheck", status: "success", durationMs: 42, detail: "User authorized for eng_002" },
      { node: "queryRouter", status: "success", durationMs: 110, detail: "Routed to hybrid mode" },
      { node: "retrieve", status: "success", durationMs: 920, detail: "Retrieved 12 chunks, reranked to top 5" },
      { node: "generate", status: "success", durationMs: 440, detail: "Generated answer with 3 citations" },
      { node: "guardrails", status: "success", durationMs: 18, detail: "Passed all guardrails" },
      { node: "logAuditTrail", status: "success", durationMs: 30, detail: "Logged to audit trail" },
    ],
    timestamp: "2025-06-09T10:30:00Z",
  },
  {
    id: "ql_004",
    userId: "usr_003",
    userName: "James Wilson",
    engagementId: "eng_003",
    engagementName: "GDPR Compliance Assessment",
    query: "What GDPR articles apply to data processor agreements?",
    runId: "run_jkl012",
    retrievalMode: "vector",
    confidence: 0.88,
    latencyMs: 1100,
    citationCount: 2,
    agentSteps: [
      { node: "policyCheck", status: "success", durationMs: 40, detail: "User authorized for eng_003" },
      { node: "queryRouter", status: "success", durationMs: 85, detail: "Routed to vector mode" },
      { node: "retrieve", status: "success", durationMs: 550, detail: "Retrieved 6 chunks, reranked to top 3" },
      { node: "generate", status: "success", durationMs: 390, detail: "Generated answer with 2 citations" },
      { node: "guardrails", status: "success", durationMs: 15, detail: "Passed all guardrails" },
      { node: "logAuditTrail", status: "success", durationMs: 20, detail: "Logged to audit trail" },
    ],
    timestamp: "2025-06-08T15:45:00Z",
  },
];

// ── System Health ────────────────────────────────────────────────────
export const mockServiceHealth: ServiceHealth[] = [
  {
    name: "audit-assistant-ui",
    status: "healthy",
    version: "0.2.0",
    uptime: "14d 6h 23m",
    latencyMs: 45,
    lastChecked: "2025-06-10T14:30:00Z",
    details: { nextVersion: "14.2.0", nodeVersion: "20.11.0" },
  },
  {
    name: "audit-assistant-api",
    status: "healthy",
    version: "0.2.0",
    uptime: "14d 6h 23m",
    latencyMs: 12,
    lastChecked: "2025-06-10T14:30:00Z",
    details: { nestVersion: "10.3.0", prismaVersion: "5.10.0" },
  },
  {
    name: "audit-rag-engine",
    status: "healthy",
    version: "0.2.0",
    uptime: "14d 5h 58m",
    latencyMs: 18,
    lastChecked: "2025-06-10T14:30:00Z",
    details: { pythonVersion: "3.12.0", fastapiVersion: "0.110.0" },
  },
  {
    name: "PostgreSQL",
    status: "healthy",
    version: "16.2",
    uptime: "30d 12h 45m",
    latencyMs: 3,
    lastChecked: "2025-06-10T14:30:00Z",
    details: { connections: 24, maxConnections: 100, dbSize: "1.2 GB" },
  },
  {
    name: "Neo4j",
    status: "healthy",
    version: "5.18.0",
    uptime: "30d 12h 45m",
    latencyMs: 8,
    lastChecked: "2025-06-10T14:30:00Z",
    details: { nodes: 15420, relationships: 42680, storeSize: "890 MB" },
  },
  {
    name: "MongoDB",
    status: "healthy",
    version: "7.0.5",
    uptime: "30d 12h 45m",
    latencyMs: 5,
    lastChecked: "2025-06-10T14:30:00Z",
    details: { documents: 8940, collections: 6, dataSize: "2.4 GB" },
  },
  {
    name: "MinIO (S3)",
    status: "degraded",
    version: "2024.03.15",
    uptime: "2d 4h 12m",
    latencyMs: 120,
    lastChecked: "2025-06-10T14:30:00Z",
    details: { buckets: 3, totalObjects: 412, usedStorage: "4.8 GB", note: "High latency detected" },
  },
];

export const mockSystemMetrics: SystemMetric[] = [
  { label: "Avg Query Latency", value: 1150, unit: "ms", trend: "down", changePercent: -8 },
  { label: "Queries Today", value: 47, unit: "", trend: "up", changePercent: 12 },
  { label: "Avg Confidence", value: 0.86, unit: "", trend: "stable", changePercent: 0 },
  { label: "Error Rate", value: 0.02, unit: "%", trend: "down", changePercent: -15 },
  { label: "Documents Indexed", value: 193, unit: "", trend: "up", changePercent: 5 },
  { label: "Active Sessions", value: 3, unit: "", trend: "stable", changePercent: 0 },
];

// ── AI Governance ────────────────────────────────────────────────────
export const mockModelCards: ModelCard[] = [
  {
    id: "mc_001",
    name: "GPT-4o",
    provider: "OpenAI",
    version: "gpt-4o-2024-08-06",
    contextWindow: 128000,
    purpose: "Primary generation model for Q&A, workpaper drafting, and finding generation",
    knownLimitations: [
      "May hallucinate citations if not properly grounded",
      "Context window may be insufficient for very large document sets",
      "Token cost is higher than alternatives",
      "No guaranteed consistency across regenerations",
    ],
    lastUpdated: "2025-01-15T08:00:00Z",
  },
  {
    id: "mc_002",
    name: "text-embedding-3-large",
    provider: "OpenAI",
    version: "text-embedding-3-large",
    contextWindow: 8191,
    purpose: "Embedding model for document chunks and queries (3072 dimensions)",
    knownLimitations: [
      "Fixed dimension output; dimensionality reduction may reduce precision",
      "English-optimized; multilingual performance may vary",
      "Cannot embed images or non-text content",
    ],
    lastUpdated: "2025-01-15T08:00:00Z",
  },
  {
    id: "mc_003",
    name: "GPT-4o-mini",
    provider: "OpenAI",
    version: "gpt-4o-mini-2024-07-18",
    contextWindow: 128000,
    purpose: "Query routing, entity extraction, and lightweight classification tasks",
    knownLimitations: [
      "Lower accuracy on complex reasoning tasks vs GPT-4o",
      "May miss nuanced audit-specific terminology",
    ],
    lastUpdated: "2025-01-15T08:00:00Z",
  },
];

export const mockKillSwitch: KillSwitchState = {
  level: "active",
};

export const mockGoalDriftAlerts: GoalDriftAlert[] = [
  {
    id: "gd_001",
    agentGraph: "AuditQueryGraph",
    metric: "citation_precision",
    expected: 0.90,
    actual: 0.82,
    severity: "warning",
    timestamp: "2025-06-09T16:00:00Z",
    resolved: false,
  },
  {
    id: "gd_002",
    agentGraph: "AuditQueryGraph",
    metric: "abstention_rate",
    expected: 0.15,
    actual: 0.08,
    severity: "warning",
    timestamp: "2025-06-08T10:00:00Z",
    resolved: true,
  },
];

// ── Approval Requests ────────────────────────────────────────────────
export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: "apr_001",
    entityType: "finding",
    entityId: "fnd_001",
    entityTitle: "Incomplete Background Verification for Contract Staff",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    requestedBy: "James Wilson",
    requestedAt: "2025-06-05T10:30:00Z",
    status: "approved",
    reviewedBy: "Sarah Chen",
    reviewedAt: "2025-06-06T09:00:00Z",
    comment: "Reviewed and approved. Well-documented finding.",
  },
  {
    id: "apr_002",
    entityType: "finding",
    entityId: "fnd_002",
    entityTitle: "Cloud Service Security Assessment Not Formalized",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    requestedBy: "Maria Garcia",
    requestedAt: "2025-06-06T12:00:00Z",
    status: "pending",
  },
  {
    id: "apr_003",
    entityType: "workpaper",
    entityId: "wp_001",
    entityTitle: "Privileged Access Management - Test of Controls",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    requestedBy: "James Wilson",
    requestedAt: "2025-06-07T09:00:00Z",
    status: "approved",
    reviewedBy: "Sarah Chen",
    reviewedAt: "2025-06-08T14:00:00Z",
    comment: "Test procedures and results are complete.",
  },
  {
    id: "apr_004",
    entityType: "workpaper",
    entityId: "wp_002",
    entityTitle: "Information Security Policy - Walkthrough",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    requestedBy: "Maria Garcia",
    requestedAt: "2025-06-08T10:00:00Z",
    status: "revision_requested",
    reviewedBy: "Sarah Chen",
    reviewedAt: "2025-06-08T16:00:00Z",
    comment: "Condition and testing sections need more detail. Please expand with specific evidence references.",
  },
  {
    id: "apr_005",
    entityType: "finding",
    entityId: "fnd_003",
    entityTitle: "SIEM Alert Tuning Documentation Missing",
    engagementId: "eng_001",
    engagementName: "ISO 27001 ISMS Audit 2025",
    requestedBy: "James Wilson",
    requestedAt: "2025-06-09T11:00:00Z",
    status: "pending",
  },
];
